services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: ddbj-search-front-dev
    container_name: ddbj-search-front-dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:6006:6006
    restart: on-failure
    working_dir: /app
    entrypoint: ["tini", "--"]
    command: ["sleep", "infinity"]
    networks:
      - ddbj-search-network-dev

volumes:
  node_modules:
    name: ddbj-search-front-dev-node_modules

networks:
  ddbj-search-network-dev:
    name: ddbj-search-network-dev
