FROM node:18.20.0-bookworm-slim

RUN corepack enable

WORKDIR /app
COPY package.json pnpm-lock.yaml /app/

ENV PNPM_STORE_DIR=/app/.pnpm-store
RUN pnpm install --frozen-lockfile

COPY . .

# App
EXPOSE 3000
# Storybook
EXPOSE 6006

ENTRYPOINT [""]
CMD ["sleep", "infinity"]
