FROM node:18.20.0-bookworm-slim

RUN apt update && \
    apt install -y --no-install-recommends \
    tini && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN corepack enable

WORKDIR /app
COPY package.json pnpm-lock.yaml /app/

RUN pnpm install --frozen-lockfile

COPY . .

# App
EXPOSE 3000
# Storybook
EXPOSE 6006

ENTRYPOINT ["tini", "--"]
CMD ["sleep", "infinity"]
