[[redirects]]
from = "/search/detail/*"
to = "/"
status = 200
force = true

[[redirects]]
from = "/search/en/*"
to = "/"
status = 200
force = true

[[redirects]]
  from = "/search/*"
  to = "/:splat"
  status = 200
  force = true

