import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: [],
  categories: {
    correctness: "off",
  },
  env: {
    builtin: true,
  },
  ignorePatterns: ["dist", "src/routeTree.gen.ts"],
  overrides: [
    {
      files: ["**/*.{ts,tsx,js}"],
      rules: {
        "constructor-super": "off",
        "for-direction": "error",
        "no-async-promise-executor": "error",
        "no-case-declarations": "error",
        "no-class-assign": "off",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "off",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-delete-var": "error",
        "no-dupe-class-members": "off",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "off",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-empty-pattern": "off",
        "no-empty-static-block": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-fallthrough": "error",
        "no-func-assign": "off",
        "no-global-assign": "error",
        "no-import-assign": "off",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-native-nonconstructor": "off",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "off",
        "no-prototype-builtins": "error",
        "no-redeclare": "off",
        "no-regex-spaces": "error",
        "no-self-assign": "error",
        "no-setter-return": "off",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "off",
        "no-unexpected-multiline": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "off",
        "no-unsafe-optional-chaining": "error",
        "no-unused-labels": "error",
        "no-unused-private-class-members": "error",
        "no-unused-vars": [
          "warn",
          {
            argsIgnorePattern: "^_",
            ignoreRestSiblings: true,
          },
        ],
        "no-useless-backreference": "error",
        "no-useless-catch": "error",
        "no-useless-escape": "error",
        "no-with": "off",
        "require-yield": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
        "no-var": "error",
        "prefer-const": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "no-array-constructor": "error",
        "no-unused-expressions": [
          "error",
          {
            allowTernary: true,
          },
        ],
        "typescript/ban-ts-comment": "error",
        "typescript/no-duplicate-enum-values": "error",
        "typescript/no-empty-object-type": "off",
        "typescript/no-explicit-any": "error",
        "typescript/no-extra-non-null-assertion": "error",
        "typescript/no-misused-new": "error",
        "typescript/no-namespace": "error",
        "typescript/no-non-null-asserted-optional-chain": "error",
        "typescript/no-require-imports": "error",
        "typescript/no-this-alias": "error",
        "typescript/no-unnecessary-type-constraint": "error",
        "typescript/no-unsafe-declaration-merging": "error",
        "typescript/no-unsafe-function-type": "error",
        "typescript/no-wrapper-object-types": "error",
        "typescript/prefer-as-const": "error",
        "typescript/prefer-namespace-keyword": "error",
        "typescript/triple-slash-reference": "error",
        "@tanstack/router/create-route-property-order": "warn",
        "@tanstack/router/route-param-names": "error",
        "import/namespace": "error",
        "import/default": "error",
        "import/no-named-as-default": "warn",
        "import/no-named-as-default-member": "warn",
        "import/no-duplicates": "warn",
        "react/rules-of-hooks": "error",
        "react/exhaustive-deps": "warn",
        "react/only-export-components": [
          "warn",
          {
            allowConstantExport: true,
          },
        ],
      },
      plugins: ["typescript", "import", "react"],
      jsPlugins: ["@tanstack/eslint-plugin-router"],
      env: {
        es2018: true,
        es2020: true,
        browser: true,
      },
      globals: {
        AudioWorkletGlobalScope: "readonly",
        AudioWorkletProcessor: "readonly",
        currentFrame: "readonly",
        currentTime: "readonly",
        registerProcessor: "readonly",
        sampleRate: "readonly",
        WorkletGlobalScope: "readonly",
      },
    },
    {
      files: ["**/*.stories.@(ts|tsx|js|jsx|mjs|cjs)", "**/*.story.@(ts|tsx|js|jsx|mjs|cjs)"],
      rules: {
        "storybook/await-interactions": "error",
        "storybook/context-in-play-function": "error",
        "storybook/default-exports": "error",
        "storybook/hierarchy-separator": "warn",
        "storybook/no-redundant-story-name": "warn",
        "storybook/no-renderer-packages": "error",
        "storybook/prefer-pascal-case": "warn",
        "storybook/story-exports": "error",
        "storybook/use-storybook-expect": "error",
        "storybook/use-storybook-testing-library": "error",
        "import/no-anonymous-default-export": "off",
        "react/rules-of-hooks": "off",
      },
      jsPlugins: ["eslint-plugin-storybook"],
      plugins: ["react", "import"],
    },
    {
      files: [".storybook/main.@(js|cjs|mjs|ts)"],
      rules: {
        "storybook/no-uninstalled-addons": "error",
      },
      jsPlugins: ["eslint-plugin-storybook"],
    },
  ],
});
