/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiDocRouteImport } from './routes/api-doc'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntryIndexRouteImport } from './routes/entry/index'
import { Route as EntrySraSubmissionIndexRouteImport } from './routes/entry/sra-submission/index'
import { Route as EntrySraStudyIndexRouteImport } from './routes/entry/sra-study/index'
import { Route as EntrySraSampleIndexRouteImport } from './routes/entry/sra-sample/index'
import { Route as EntrySraRunIndexRouteImport } from './routes/entry/sra-run/index'
import { Route as EntrySraExperimentIndexRouteImport } from './routes/entry/sra-experiment/index'
import { Route as EntrySraAnalysisIndexRouteImport } from './routes/entry/sra-analysis/index'
import { Route as EntryJgaStudyIndexRouteImport } from './routes/entry/jga-study/index'
import { Route as EntryJgaPolicyIndexRouteImport } from './routes/entry/jga-policy/index'
import { Route as EntryJgaDatasetIndexRouteImport } from './routes/entry/jga-dataset/index'
import { Route as EntryJgaDacIndexRouteImport } from './routes/entry/jga-dac/index'
import { Route as EntryBiosampleIndexRouteImport } from './routes/entry/biosample/index'
import { Route as EntryBioprojectIndexRouteImport } from './routes/entry/bioproject/index'
import { Route as EntrySraSubmissionIdentifierRouteImport } from './routes/entry/sra-submission/$identifier'
import { Route as EntrySraStudyIdentifierRouteImport } from './routes/entry/sra-study/$identifier'
import { Route as EntrySraSampleIdentifierRouteImport } from './routes/entry/sra-sample/$identifier'
import { Route as EntrySraRunIdentifierRouteImport } from './routes/entry/sra-run/$identifier'
import { Route as EntrySraExperimentIdentifierRouteImport } from './routes/entry/sra-experiment/$identifier'
import { Route as EntrySraAnalysisIdentifierRouteImport } from './routes/entry/sra-analysis/$identifier'
import { Route as EntryJgaStudyIdentifierRouteImport } from './routes/entry/jga-study/$identifier'
import { Route as EntryJgaPolicyIdentifierRouteImport } from './routes/entry/jga-policy/$identifier'
import { Route as EntryJgaDatasetIdentifierRouteImport } from './routes/entry/jga-dataset/$identifier'
import { Route as EntryJgaDacIdentifierRouteImport } from './routes/entry/jga-dac/$identifier'
import { Route as EntryBiosampleIdentifierRouteImport } from './routes/entry/biosample/$identifier'
import { Route as EntryBioprojectIdentifierRouteImport } from './routes/entry/bioproject/$identifier'

const ApiDocRoute = ApiDocRouteImport.update({
  id: '/api-doc',
  path: '/api-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryIndexRoute = EntryIndexRouteImport.update({
  id: '/entry/',
  path: '/entry/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrySraSubmissionIndexRoute = EntrySraSubmissionIndexRouteImport.update({
  id: '/entry/sra-submission/',
  path: '/entry/sra-submission/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrySraStudyIndexRoute = EntrySraStudyIndexRouteImport.update({
  id: '/entry/sra-study/',
  path: '/entry/sra-study/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrySraSampleIndexRoute = EntrySraSampleIndexRouteImport.update({
  id: '/entry/sra-sample/',
  path: '/entry/sra-sample/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrySraRunIndexRoute = EntrySraRunIndexRouteImport.update({
  id: '/entry/sra-run/',
  path: '/entry/sra-run/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrySraExperimentIndexRoute = EntrySraExperimentIndexRouteImport.update({
  id: '/entry/sra-experiment/',
  path: '/entry/sra-experiment/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrySraAnalysisIndexRoute = EntrySraAnalysisIndexRouteImport.update({
  id: '/entry/sra-analysis/',
  path: '/entry/sra-analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryJgaStudyIndexRoute = EntryJgaStudyIndexRouteImport.update({
  id: '/entry/jga-study/',
  path: '/entry/jga-study/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryJgaPolicyIndexRoute = EntryJgaPolicyIndexRouteImport.update({
  id: '/entry/jga-policy/',
  path: '/entry/jga-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryJgaDatasetIndexRoute = EntryJgaDatasetIndexRouteImport.update({
  id: '/entry/jga-dataset/',
  path: '/entry/jga-dataset/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryJgaDacIndexRoute = EntryJgaDacIndexRouteImport.update({
  id: '/entry/jga-dac/',
  path: '/entry/jga-dac/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryBiosampleIndexRoute = EntryBiosampleIndexRouteImport.update({
  id: '/entry/biosample/',
  path: '/entry/biosample/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryBioprojectIndexRoute = EntryBioprojectIndexRouteImport.update({
  id: '/entry/bioproject/',
  path: '/entry/bioproject/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrySraSubmissionIdentifierRoute =
  EntrySraSubmissionIdentifierRouteImport.update({
    id: '/entry/sra-submission/$identifier',
    path: '/entry/sra-submission/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntrySraStudyIdentifierRoute = EntrySraStudyIdentifierRouteImport.update({
  id: '/entry/sra-study/$identifier',
  path: '/entry/sra-study/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrySraSampleIdentifierRoute =
  EntrySraSampleIdentifierRouteImport.update({
    id: '/entry/sra-sample/$identifier',
    path: '/entry/sra-sample/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntrySraRunIdentifierRoute = EntrySraRunIdentifierRouteImport.update({
  id: '/entry/sra-run/$identifier',
  path: '/entry/sra-run/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrySraExperimentIdentifierRoute =
  EntrySraExperimentIdentifierRouteImport.update({
    id: '/entry/sra-experiment/$identifier',
    path: '/entry/sra-experiment/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntrySraAnalysisIdentifierRoute =
  EntrySraAnalysisIdentifierRouteImport.update({
    id: '/entry/sra-analysis/$identifier',
    path: '/entry/sra-analysis/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntryJgaStudyIdentifierRoute = EntryJgaStudyIdentifierRouteImport.update({
  id: '/entry/jga-study/$identifier',
  path: '/entry/jga-study/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryJgaPolicyIdentifierRoute =
  EntryJgaPolicyIdentifierRouteImport.update({
    id: '/entry/jga-policy/$identifier',
    path: '/entry/jga-policy/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntryJgaDatasetIdentifierRoute =
  EntryJgaDatasetIdentifierRouteImport.update({
    id: '/entry/jga-dataset/$identifier',
    path: '/entry/jga-dataset/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntryJgaDacIdentifierRoute = EntryJgaDacIdentifierRouteImport.update({
  id: '/entry/jga-dac/$identifier',
  path: '/entry/jga-dac/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryBiosampleIdentifierRoute =
  EntryBiosampleIdentifierRouteImport.update({
    id: '/entry/biosample/$identifier',
    path: '/entry/biosample/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntryBioprojectIdentifierRoute =
  EntryBioprojectIdentifierRouteImport.update({
    id: '/entry/bioproject/$identifier',
    path: '/entry/bioproject/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-doc': typeof ApiDocRoute
  '/entry': typeof EntryIndexRoute
  '/entry/bioproject/$identifier': typeof EntryBioprojectIdentifierRoute
  '/entry/biosample/$identifier': typeof EntryBiosampleIdentifierRoute
  '/entry/jga-dac/$identifier': typeof EntryJgaDacIdentifierRoute
  '/entry/jga-dataset/$identifier': typeof EntryJgaDatasetIdentifierRoute
  '/entry/jga-policy/$identifier': typeof EntryJgaPolicyIdentifierRoute
  '/entry/jga-study/$identifier': typeof EntryJgaStudyIdentifierRoute
  '/entry/sra-analysis/$identifier': typeof EntrySraAnalysisIdentifierRoute
  '/entry/sra-experiment/$identifier': typeof EntrySraExperimentIdentifierRoute
  '/entry/sra-run/$identifier': typeof EntrySraRunIdentifierRoute
  '/entry/sra-sample/$identifier': typeof EntrySraSampleIdentifierRoute
  '/entry/sra-study/$identifier': typeof EntrySraStudyIdentifierRoute
  '/entry/sra-submission/$identifier': typeof EntrySraSubmissionIdentifierRoute
  '/entry/bioproject': typeof EntryBioprojectIndexRoute
  '/entry/biosample': typeof EntryBiosampleIndexRoute
  '/entry/jga-dac': typeof EntryJgaDacIndexRoute
  '/entry/jga-dataset': typeof EntryJgaDatasetIndexRoute
  '/entry/jga-policy': typeof EntryJgaPolicyIndexRoute
  '/entry/jga-study': typeof EntryJgaStudyIndexRoute
  '/entry/sra-analysis': typeof EntrySraAnalysisIndexRoute
  '/entry/sra-experiment': typeof EntrySraExperimentIndexRoute
  '/entry/sra-run': typeof EntrySraRunIndexRoute
  '/entry/sra-sample': typeof EntrySraSampleIndexRoute
  '/entry/sra-study': typeof EntrySraStudyIndexRoute
  '/entry/sra-submission': typeof EntrySraSubmissionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-doc': typeof ApiDocRoute
  '/entry': typeof EntryIndexRoute
  '/entry/bioproject/$identifier': typeof EntryBioprojectIdentifierRoute
  '/entry/biosample/$identifier': typeof EntryBiosampleIdentifierRoute
  '/entry/jga-dac/$identifier': typeof EntryJgaDacIdentifierRoute
  '/entry/jga-dataset/$identifier': typeof EntryJgaDatasetIdentifierRoute
  '/entry/jga-policy/$identifier': typeof EntryJgaPolicyIdentifierRoute
  '/entry/jga-study/$identifier': typeof EntryJgaStudyIdentifierRoute
  '/entry/sra-analysis/$identifier': typeof EntrySraAnalysisIdentifierRoute
  '/entry/sra-experiment/$identifier': typeof EntrySraExperimentIdentifierRoute
  '/entry/sra-run/$identifier': typeof EntrySraRunIdentifierRoute
  '/entry/sra-sample/$identifier': typeof EntrySraSampleIdentifierRoute
  '/entry/sra-study/$identifier': typeof EntrySraStudyIdentifierRoute
  '/entry/sra-submission/$identifier': typeof EntrySraSubmissionIdentifierRoute
  '/entry/bioproject': typeof EntryBioprojectIndexRoute
  '/entry/biosample': typeof EntryBiosampleIndexRoute
  '/entry/jga-dac': typeof EntryJgaDacIndexRoute
  '/entry/jga-dataset': typeof EntryJgaDatasetIndexRoute
  '/entry/jga-policy': typeof EntryJgaPolicyIndexRoute
  '/entry/jga-study': typeof EntryJgaStudyIndexRoute
  '/entry/sra-analysis': typeof EntrySraAnalysisIndexRoute
  '/entry/sra-experiment': typeof EntrySraExperimentIndexRoute
  '/entry/sra-run': typeof EntrySraRunIndexRoute
  '/entry/sra-sample': typeof EntrySraSampleIndexRoute
  '/entry/sra-study': typeof EntrySraStudyIndexRoute
  '/entry/sra-submission': typeof EntrySraSubmissionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-doc': typeof ApiDocRoute
  '/entry/': typeof EntryIndexRoute
  '/entry/bioproject/$identifier': typeof EntryBioprojectIdentifierRoute
  '/entry/biosample/$identifier': typeof EntryBiosampleIdentifierRoute
  '/entry/jga-dac/$identifier': typeof EntryJgaDacIdentifierRoute
  '/entry/jga-dataset/$identifier': typeof EntryJgaDatasetIdentifierRoute
  '/entry/jga-policy/$identifier': typeof EntryJgaPolicyIdentifierRoute
  '/entry/jga-study/$identifier': typeof EntryJgaStudyIdentifierRoute
  '/entry/sra-analysis/$identifier': typeof EntrySraAnalysisIdentifierRoute
  '/entry/sra-experiment/$identifier': typeof EntrySraExperimentIdentifierRoute
  '/entry/sra-run/$identifier': typeof EntrySraRunIdentifierRoute
  '/entry/sra-sample/$identifier': typeof EntrySraSampleIdentifierRoute
  '/entry/sra-study/$identifier': typeof EntrySraStudyIdentifierRoute
  '/entry/sra-submission/$identifier': typeof EntrySraSubmissionIdentifierRoute
  '/entry/bioproject/': typeof EntryBioprojectIndexRoute
  '/entry/biosample/': typeof EntryBiosampleIndexRoute
  '/entry/jga-dac/': typeof EntryJgaDacIndexRoute
  '/entry/jga-dataset/': typeof EntryJgaDatasetIndexRoute
  '/entry/jga-policy/': typeof EntryJgaPolicyIndexRoute
  '/entry/jga-study/': typeof EntryJgaStudyIndexRoute
  '/entry/sra-analysis/': typeof EntrySraAnalysisIndexRoute
  '/entry/sra-experiment/': typeof EntrySraExperimentIndexRoute
  '/entry/sra-run/': typeof EntrySraRunIndexRoute
  '/entry/sra-sample/': typeof EntrySraSampleIndexRoute
  '/entry/sra-study/': typeof EntrySraStudyIndexRoute
  '/entry/sra-submission/': typeof EntrySraSubmissionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-doc'
    | '/entry'
    | '/entry/bioproject/$identifier'
    | '/entry/biosample/$identifier'
    | '/entry/jga-dac/$identifier'
    | '/entry/jga-dataset/$identifier'
    | '/entry/jga-policy/$identifier'
    | '/entry/jga-study/$identifier'
    | '/entry/sra-analysis/$identifier'
    | '/entry/sra-experiment/$identifier'
    | '/entry/sra-run/$identifier'
    | '/entry/sra-sample/$identifier'
    | '/entry/sra-study/$identifier'
    | '/entry/sra-submission/$identifier'
    | '/entry/bioproject'
    | '/entry/biosample'
    | '/entry/jga-dac'
    | '/entry/jga-dataset'
    | '/entry/jga-policy'
    | '/entry/jga-study'
    | '/entry/sra-analysis'
    | '/entry/sra-experiment'
    | '/entry/sra-run'
    | '/entry/sra-sample'
    | '/entry/sra-study'
    | '/entry/sra-submission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-doc'
    | '/entry'
    | '/entry/bioproject/$identifier'
    | '/entry/biosample/$identifier'
    | '/entry/jga-dac/$identifier'
    | '/entry/jga-dataset/$identifier'
    | '/entry/jga-policy/$identifier'
    | '/entry/jga-study/$identifier'
    | '/entry/sra-analysis/$identifier'
    | '/entry/sra-experiment/$identifier'
    | '/entry/sra-run/$identifier'
    | '/entry/sra-sample/$identifier'
    | '/entry/sra-study/$identifier'
    | '/entry/sra-submission/$identifier'
    | '/entry/bioproject'
    | '/entry/biosample'
    | '/entry/jga-dac'
    | '/entry/jga-dataset'
    | '/entry/jga-policy'
    | '/entry/jga-study'
    | '/entry/sra-analysis'
    | '/entry/sra-experiment'
    | '/entry/sra-run'
    | '/entry/sra-sample'
    | '/entry/sra-study'
    | '/entry/sra-submission'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-doc'
    | '/entry/'
    | '/entry/bioproject/$identifier'
    | '/entry/biosample/$identifier'
    | '/entry/jga-dac/$identifier'
    | '/entry/jga-dataset/$identifier'
    | '/entry/jga-policy/$identifier'
    | '/entry/jga-study/$identifier'
    | '/entry/sra-analysis/$identifier'
    | '/entry/sra-experiment/$identifier'
    | '/entry/sra-run/$identifier'
    | '/entry/sra-sample/$identifier'
    | '/entry/sra-study/$identifier'
    | '/entry/sra-submission/$identifier'
    | '/entry/bioproject/'
    | '/entry/biosample/'
    | '/entry/jga-dac/'
    | '/entry/jga-dataset/'
    | '/entry/jga-policy/'
    | '/entry/jga-study/'
    | '/entry/sra-analysis/'
    | '/entry/sra-experiment/'
    | '/entry/sra-run/'
    | '/entry/sra-sample/'
    | '/entry/sra-study/'
    | '/entry/sra-submission/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiDocRoute: typeof ApiDocRoute
  EntryIndexRoute: typeof EntryIndexRoute
  EntryBioprojectIdentifierRoute: typeof EntryBioprojectIdentifierRoute
  EntryBiosampleIdentifierRoute: typeof EntryBiosampleIdentifierRoute
  EntryJgaDacIdentifierRoute: typeof EntryJgaDacIdentifierRoute
  EntryJgaDatasetIdentifierRoute: typeof EntryJgaDatasetIdentifierRoute
  EntryJgaPolicyIdentifierRoute: typeof EntryJgaPolicyIdentifierRoute
  EntryJgaStudyIdentifierRoute: typeof EntryJgaStudyIdentifierRoute
  EntrySraAnalysisIdentifierRoute: typeof EntrySraAnalysisIdentifierRoute
  EntrySraExperimentIdentifierRoute: typeof EntrySraExperimentIdentifierRoute
  EntrySraRunIdentifierRoute: typeof EntrySraRunIdentifierRoute
  EntrySraSampleIdentifierRoute: typeof EntrySraSampleIdentifierRoute
  EntrySraStudyIdentifierRoute: typeof EntrySraStudyIdentifierRoute
  EntrySraSubmissionIdentifierRoute: typeof EntrySraSubmissionIdentifierRoute
  EntryBioprojectIndexRoute: typeof EntryBioprojectIndexRoute
  EntryBiosampleIndexRoute: typeof EntryBiosampleIndexRoute
  EntryJgaDacIndexRoute: typeof EntryJgaDacIndexRoute
  EntryJgaDatasetIndexRoute: typeof EntryJgaDatasetIndexRoute
  EntryJgaPolicyIndexRoute: typeof EntryJgaPolicyIndexRoute
  EntryJgaStudyIndexRoute: typeof EntryJgaStudyIndexRoute
  EntrySraAnalysisIndexRoute: typeof EntrySraAnalysisIndexRoute
  EntrySraExperimentIndexRoute: typeof EntrySraExperimentIndexRoute
  EntrySraRunIndexRoute: typeof EntrySraRunIndexRoute
  EntrySraSampleIndexRoute: typeof EntrySraSampleIndexRoute
  EntrySraStudyIndexRoute: typeof EntrySraStudyIndexRoute
  EntrySraSubmissionIndexRoute: typeof EntrySraSubmissionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api-doc': {
      id: '/api-doc'
      path: '/api-doc'
      fullPath: '/api-doc'
      preLoaderRoute: typeof ApiDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/': {
      id: '/entry/'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-submission/': {
      id: '/entry/sra-submission/'
      path: '/entry/sra-submission'
      fullPath: '/entry/sra-submission'
      preLoaderRoute: typeof EntrySraSubmissionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-study/': {
      id: '/entry/sra-study/'
      path: '/entry/sra-study'
      fullPath: '/entry/sra-study'
      preLoaderRoute: typeof EntrySraStudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-sample/': {
      id: '/entry/sra-sample/'
      path: '/entry/sra-sample'
      fullPath: '/entry/sra-sample'
      preLoaderRoute: typeof EntrySraSampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-run/': {
      id: '/entry/sra-run/'
      path: '/entry/sra-run'
      fullPath: '/entry/sra-run'
      preLoaderRoute: typeof EntrySraRunIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-experiment/': {
      id: '/entry/sra-experiment/'
      path: '/entry/sra-experiment'
      fullPath: '/entry/sra-experiment'
      preLoaderRoute: typeof EntrySraExperimentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-analysis/': {
      id: '/entry/sra-analysis/'
      path: '/entry/sra-analysis'
      fullPath: '/entry/sra-analysis'
      preLoaderRoute: typeof EntrySraAnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/jga-study/': {
      id: '/entry/jga-study/'
      path: '/entry/jga-study'
      fullPath: '/entry/jga-study'
      preLoaderRoute: typeof EntryJgaStudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/jga-policy/': {
      id: '/entry/jga-policy/'
      path: '/entry/jga-policy'
      fullPath: '/entry/jga-policy'
      preLoaderRoute: typeof EntryJgaPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/jga-dataset/': {
      id: '/entry/jga-dataset/'
      path: '/entry/jga-dataset'
      fullPath: '/entry/jga-dataset'
      preLoaderRoute: typeof EntryJgaDatasetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/jga-dac/': {
      id: '/entry/jga-dac/'
      path: '/entry/jga-dac'
      fullPath: '/entry/jga-dac'
      preLoaderRoute: typeof EntryJgaDacIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/biosample/': {
      id: '/entry/biosample/'
      path: '/entry/biosample'
      fullPath: '/entry/biosample'
      preLoaderRoute: typeof EntryBiosampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/bioproject/': {
      id: '/entry/bioproject/'
      path: '/entry/bioproject'
      fullPath: '/entry/bioproject'
      preLoaderRoute: typeof EntryBioprojectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-submission/$identifier': {
      id: '/entry/sra-submission/$identifier'
      path: '/entry/sra-submission/$identifier'
      fullPath: '/entry/sra-submission/$identifier'
      preLoaderRoute: typeof EntrySraSubmissionIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-study/$identifier': {
      id: '/entry/sra-study/$identifier'
      path: '/entry/sra-study/$identifier'
      fullPath: '/entry/sra-study/$identifier'
      preLoaderRoute: typeof EntrySraStudyIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-sample/$identifier': {
      id: '/entry/sra-sample/$identifier'
      path: '/entry/sra-sample/$identifier'
      fullPath: '/entry/sra-sample/$identifier'
      preLoaderRoute: typeof EntrySraSampleIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-run/$identifier': {
      id: '/entry/sra-run/$identifier'
      path: '/entry/sra-run/$identifier'
      fullPath: '/entry/sra-run/$identifier'
      preLoaderRoute: typeof EntrySraRunIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-experiment/$identifier': {
      id: '/entry/sra-experiment/$identifier'
      path: '/entry/sra-experiment/$identifier'
      fullPath: '/entry/sra-experiment/$identifier'
      preLoaderRoute: typeof EntrySraExperimentIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/sra-analysis/$identifier': {
      id: '/entry/sra-analysis/$identifier'
      path: '/entry/sra-analysis/$identifier'
      fullPath: '/entry/sra-analysis/$identifier'
      preLoaderRoute: typeof EntrySraAnalysisIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/jga-study/$identifier': {
      id: '/entry/jga-study/$identifier'
      path: '/entry/jga-study/$identifier'
      fullPath: '/entry/jga-study/$identifier'
      preLoaderRoute: typeof EntryJgaStudyIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/jga-policy/$identifier': {
      id: '/entry/jga-policy/$identifier'
      path: '/entry/jga-policy/$identifier'
      fullPath: '/entry/jga-policy/$identifier'
      preLoaderRoute: typeof EntryJgaPolicyIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/jga-dataset/$identifier': {
      id: '/entry/jga-dataset/$identifier'
      path: '/entry/jga-dataset/$identifier'
      fullPath: '/entry/jga-dataset/$identifier'
      preLoaderRoute: typeof EntryJgaDatasetIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/jga-dac/$identifier': {
      id: '/entry/jga-dac/$identifier'
      path: '/entry/jga-dac/$identifier'
      fullPath: '/entry/jga-dac/$identifier'
      preLoaderRoute: typeof EntryJgaDacIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/biosample/$identifier': {
      id: '/entry/biosample/$identifier'
      path: '/entry/biosample/$identifier'
      fullPath: '/entry/biosample/$identifier'
      preLoaderRoute: typeof EntryBiosampleIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/bioproject/$identifier': {
      id: '/entry/bioproject/$identifier'
      path: '/entry/bioproject/$identifier'
      fullPath: '/entry/bioproject/$identifier'
      preLoaderRoute: typeof EntryBioprojectIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiDocRoute: ApiDocRoute,
  EntryIndexRoute: EntryIndexRoute,
  EntryBioprojectIdentifierRoute: EntryBioprojectIdentifierRoute,
  EntryBiosampleIdentifierRoute: EntryBiosampleIdentifierRoute,
  EntryJgaDacIdentifierRoute: EntryJgaDacIdentifierRoute,
  EntryJgaDatasetIdentifierRoute: EntryJgaDatasetIdentifierRoute,
  EntryJgaPolicyIdentifierRoute: EntryJgaPolicyIdentifierRoute,
  EntryJgaStudyIdentifierRoute: EntryJgaStudyIdentifierRoute,
  EntrySraAnalysisIdentifierRoute: EntrySraAnalysisIdentifierRoute,
  EntrySraExperimentIdentifierRoute: EntrySraExperimentIdentifierRoute,
  EntrySraRunIdentifierRoute: EntrySraRunIdentifierRoute,
  EntrySraSampleIdentifierRoute: EntrySraSampleIdentifierRoute,
  EntrySraStudyIdentifierRoute: EntrySraStudyIdentifierRoute,
  EntrySraSubmissionIdentifierRoute: EntrySraSubmissionIdentifierRoute,
  EntryBioprojectIndexRoute: EntryBioprojectIndexRoute,
  EntryBiosampleIndexRoute: EntryBiosampleIndexRoute,
  EntryJgaDacIndexRoute: EntryJgaDacIndexRoute,
  EntryJgaDatasetIndexRoute: EntryJgaDatasetIndexRoute,
  EntryJgaPolicyIndexRoute: EntryJgaPolicyIndexRoute,
  EntryJgaStudyIndexRoute: EntryJgaStudyIndexRoute,
  EntrySraAnalysisIndexRoute: EntrySraAnalysisIndexRoute,
  EntrySraExperimentIndexRoute: EntrySraExperimentIndexRoute,
  EntrySraRunIndexRoute: EntrySraRunIndexRoute,
  EntrySraSampleIndexRoute: EntrySraSampleIndexRoute,
  EntrySraStudyIndexRoute: EntrySraStudyIndexRoute,
  EntrySraSubmissionIndexRoute: EntrySraSubmissionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
