/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchIndexImport } from './routes/search/index'
import { Route as SearchEnIndexImport } from './routes/search/en/index'
import { Route as SearchDetailIdImport } from './routes/search/detail/$id'
import { Route as SearchEnDetailIdImport } from './routes/search/en/detail/$id'

// Create/Update Routes

const SearchIndexRoute = SearchIndexImport.update({
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any)

const SearchEnIndexRoute = SearchEnIndexImport.update({
  path: '/search/en/',
  getParentRoute: () => rootRoute,
} as any)

const SearchDetailIdRoute = SearchDetailIdImport.update({
  path: '/search/detail/$id',
  getParentRoute: () => rootRoute,
} as any)

const SearchEnDetailIdRoute = SearchEnDetailIdImport.update({
  path: '/search/en/detail/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search/': {
      preLoaderRoute: typeof SearchIndexImport
      parentRoute: typeof rootRoute
    }
    '/search/detail/$id': {
      preLoaderRoute: typeof SearchDetailIdImport
      parentRoute: typeof rootRoute
    }
    '/search/en/': {
      preLoaderRoute: typeof SearchEnIndexImport
      parentRoute: typeof rootRoute
    }
    '/search/en/detail/$id': {
      preLoaderRoute: typeof SearchEnDetailIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  SearchIndexRoute,
  SearchDetailIdRoute,
  SearchEnIndexRoute,
  SearchEnDetailIdRoute,
])

/* prettier-ignore-end */
